import {cache} from 'react';
import {getDb} from './supabase';

export type CmsStatus='draft'|'published'|'archived';
export type CmsSystem={id:string;name:string;slug:string;description:string;seoTitle:string|null;seoDescription:string|null;status:CmsStatus;sortOrder:number};
export type CmsTechnology={id:string;name:string;slug:string;type:'light'|'energy'|'skin-care';definition:string;mechanism:string;seoTitle:string|null;seoDescription:string|null;status:CmsStatus;sortOrder:number;systemSlugs:string[];applicationSlugs:string[];productSlugs:string[];faqs:Array<[string,string]>};
export type CmsApplication={id:string;name:string;slug:string;description:string;outcomes:string[];clinicalDisclaimer:string|null;seoTitle:string|null;seoDescription:string|null;status:CmsStatus;sortOrder:number;systemSlugs:string[];technologySlugs:string[];productSlugs:string[]};
export type CmsProduct={id:string;slug:string;name:string;short:string;tag:string;icon:string;image?:string;systemId:string;systemGroup:string;primaryTechnologyId:string;workflowRole:string;applications:string[];applicationSlugs:string[];specs:Record<string,string>;description:string;keyFeatures:string[];regulatoryNote:string|null;aiCoreVersion:string|null;seoTitle:string|null;seoDescription:string|null;status:CmsStatus;sortOrder:number;faqs:Array<[string,string]>};
export type CmsArticle={id:string;slug:string;title:string;category:string;excerpt:string;read:string;sections:Array<{heading:string;body:string}>;systemSlugs:string[];seoTitle:string|null;seoDescription:string|null};
export type CmsPage={id:string;key:string;title:string;eyebrow:string|null;content:Record<string,unknown>;seoTitle:string|null;seoDescription:string|null};

const rows=<T>(value:{data:T[]|null;error:unknown},name:string)=>{if(value.error)throw new Error(`Unable to load CMS ${name}`);return value.data||[];};
const text=(value:unknown,fallback='')=>typeof value==='string'?value:fallback;
const strings=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];

export const getCmsSnapshot=cache(async()=>{
  const db=getDb();if(!db)throw new Error('Supabase CMS is not configured. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.');
  const [systemsResult,technologiesResult,applicationsResult,productsResult,systemTechnologiesResult,systemApplicationsResult,technologyApplicationsResult,productApplicationsResult,productImagesResult,mediaResult,pagesResult,articlesResult,articleSystemsResult,faqsResult]=await Promise.all([
    db.from('systems').select('*').eq('status','published').order('sort_order'),
    db.from('technologies').select('*').eq('status','published').order('sort_order'),
    db.from('applications').select('*').eq('status','published').order('sort_order'),
    db.from('products').select('*').eq('status','published').order('sort_order'),
    db.from('system_technologies').select('*').order('sort_order'),db.from('system_applications').select('*').order('sort_order'),db.from('technology_applications').select('*').order('sort_order'),db.from('product_applications').select('*').order('sort_order'),db.from('product_images').select('*').order('sort_order'),db.from('media_assets').select('*'),db.from('pages').select('*').eq('status','published'),db.from('articles').select('*').eq('status','published').order('published_at',{ascending:false}),db.from('article_systems').select('*'),db.from('faqs').select('*').eq('status','published').order('sort_order'),
  ]);
  const systemRows=rows(systemsResult,'systems') as any[];const technologyRows=rows(technologiesResult,'technologies') as any[];const applicationRows=rows(applicationsResult,'applications') as any[];const productRows=rows(productsResult,'products') as any[];const systemTechnologyRows=rows(systemTechnologiesResult,'system relationships') as any[];const systemApplicationRows=rows(systemApplicationsResult,'system applications') as any[];const technologyApplicationRows=rows(technologyApplicationsResult,'technology applications') as any[];const productApplicationRows=rows(productApplicationsResult,'product applications') as any[];const productImageRows=rows(productImagesResult,'product images') as any[];const mediaRows=rows(mediaResult,'media') as any[];const faqRows=rows(faqsResult,'FAQs') as any[];const articleSystemRows=rows(articleSystemsResult,'article relationships') as any[];
  const systemById=new Map(systemRows.map(row=>[row.id,row]));const technologyById=new Map(technologyRows.map(row=>[row.id,row]));const applicationById=new Map(applicationRows.map(row=>[row.id,row]));const mediaById=new Map(mediaRows.map(row=>[row.id,row]));
  const systems:CmsSystem[]=systemRows.map(row=>({id:row.id,name:row.name,slug:row.slug,description:row.description,seoTitle:row.seo_title,seoDescription:row.seo_description,status:row.status,sortOrder:row.sort_order}));
  const technologies:CmsTechnology[]=technologyRows.map(row=>({id:row.id,name:row.name,slug:row.slug,type:row.type,definition:row.definition,mechanism:row.mechanism,seoTitle:row.seo_title,seoDescription:row.seo_description,status:row.status,sortOrder:row.sort_order,systemSlugs:systemTechnologyRows.filter(link=>link.technology_id===row.id).map(link=>systemById.get(link.system_id)?.slug).filter(Boolean),applicationSlugs:technologyApplicationRows.filter(link=>link.technology_id===row.id).map(link=>applicationById.get(link.application_id)?.slug).filter(Boolean),productSlugs:productRows.filter(product=>product.primary_technology_id===row.id).map(product=>product.slug),faqs:faqRows.filter(faq=>faq.technology_id===row.id).map(faq=>[faq.question,faq.answer])}));
  const applications:CmsApplication[]=applicationRows.map(row=>({id:row.id,name:row.name,slug:row.slug,description:row.description,outcomes:strings(row.clinical_outcomes),clinicalDisclaimer:row.clinical_disclaimer,seoTitle:row.seo_title,seoDescription:row.seo_description,status:row.status,sortOrder:row.sort_order,systemSlugs:systemApplicationRows.filter(link=>link.application_id===row.id).map(link=>systemById.get(link.system_id)?.slug).filter(Boolean),technologySlugs:technologyApplicationRows.filter(link=>link.application_id===row.id).map(link=>technologyById.get(link.technology_id)?.slug).filter(Boolean),productSlugs:productApplicationRows.filter(link=>link.application_id===row.id).map(link=>productRows.find(product=>product.id===link.product_id)?.slug).filter(Boolean)}));
  const products:CmsProduct[]=productRows.map(row=>{const system=systemById.get(row.system_id);const technology=technologyById.get(row.primary_technology_id);const applicationLinks=productApplicationRows.filter(link=>link.product_id===row.id);const heroLink=productImageRows.find(link=>link.product_id===row.id&&link.role==='hero')||productImageRows.find(link=>link.product_id===row.id);const media=heroLink?mediaById.get(heroLink.media_id):null;return {id:row.id,slug:row.slug,name:row.name,short:row.short_name,tag:technology?.name||'Professional aesthetic technology',icon:'◇',image:media?.public_url,systemId:row.system_id,systemGroup:system?.name||'',primaryTechnologyId:row.primary_technology_id,workflowRole:text(row.workflow_role),applications:applicationLinks.map(link=>applicationById.get(link.application_id)?.name).filter(Boolean),applicationSlugs:applicationLinks.map(link=>applicationById.get(link.application_id)?.slug).filter(Boolean),specs:row.specs&&typeof row.specs==='object'?row.specs:{},description:row.description,keyFeatures:strings(row.key_features),regulatoryNote:row.regulatory_note,aiCoreVersion:row.ai_core_version,seoTitle:row.seo_title,seoDescription:row.seo_description,status:row.status,sortOrder:row.sort_order,faqs:faqRows.filter(faq=>faq.product_id===row.id).map(faq=>[faq.question,faq.answer])};});
  const pages:CmsPage[]=(rows(pagesResult,'pages') as any[]).map(row=>({id:row.id,key:row.key,title:row.title,eyebrow:row.eyebrow,content:row.content||{},seoTitle:row.seo_title,seoDescription:row.seo_description}));
  const articles:CmsArticle[]=(rows(articlesResult,'articles') as any[]).map(row=>({id:row.id,slug:row.slug,title:row.title,category:text(row.category,'Insight'),excerpt:text(row.excerpt),read:text(row.read_time),sections:Array.isArray(row.sections)?row.sections:[],systemSlugs:articleSystemRows.filter(link=>link.article_id===row.id).map(link=>systemById.get(link.system_id)?.slug).filter(Boolean),seoTitle:row.seo_title,seoDescription:row.seo_description}));
  return {systems,technologies,applications,products,pages,articles,faqs:faqRows.map(row=>[row.question,row.answer] as [string,string]),getSystem:(slug:string)=>systems.find(item=>item.slug===slug),getTechnology:(slug:string)=>technologies.find(item=>item.slug===slug),getApplication:(slug:string)=>applications.find(item=>item.slug===slug),getProduct:(slug:string)=>products.find(item=>item.slug===slug),getArticle:(slug:string)=>articles.find(item=>item.slug===slug),getPage:(key:string)=>pages.find(item=>item.key===key),getSystemRelations:(slug:string)=>{const system=systems.find(item=>item.slug===slug);return {technologies:technologies.filter(item=>item.systemSlugs.includes(slug)),applications:applications.filter(item=>item.systemSlugs.includes(slug)),products:products.filter(item=>item.systemId===system?.id)};}};
});

export async function validateCmsRelationships(){const cms=await getCmsSnapshot();const issues:string[]=[];for(const product of cms.products){if(!product.systemId||!cms.systems.some(system=>system.id===product.systemId))issues.push(`Product ${product.slug} has no valid system.`);if(!product.primaryTechnologyId||!cms.technologies.some(technology=>technology.id===product.primaryTechnologyId))issues.push(`Product ${product.slug} has no valid primary technology.`);if(!product.applicationSlugs.length)issues.push(`Product ${product.slug} has no application.`);if(!product.faqs.length)issues.push(`Product ${product.slug} has no FAQ.`);if(!product.seoTitle||!product.seoDescription)issues.push(`Product ${product.slug} has incomplete SEO metadata.`);if(!product.aiCoreVersion)issues.push(`Product ${product.slug} has no AI_INTELLIGENCE_CORE provenance.`);}for(const technology of cms.technologies)if(!technology.systemSlugs.length)issues.push(`Technology ${technology.slug} is orphaned.`);for(const application of cms.applications){if(!application.systemSlugs.length)issues.push(`Application ${application.slug} has no system.`);if(!application.technologySlugs.length)issues.push(`Application ${application.slug} has no technology.`);}return {valid:issues.length===0,issues};}
